### ISSUE TITLE
Error: Command failed: tuistexec

### ISSUE THREAD

**Issue by dogo** [tuist/tuist-action#6]
Hi everyone, I'm trying to set up my CI with Tuist, but I'm always receiving a tuistexec error (My log https://github.com/dogo/swdestiny-trades/runs/5528871735?check_suite_focus=true) currently, I'm using the tuist-action
to set up the Tuist environment. Anyone can help me? Thanks. I looked up some GitHub CI or any CI examples but I couldn't find any (edited)

**Comment by dogo** [comment]
I create the .tuist-version file with the current project supported Tuist version ( 3.0.1 ) and worked.

**Comment by cozzin** [comment]
Hello! @dogo
I have the same issue. Could you explain in more detail how to create `.tuist-version file with the current project supported Tuist version ( 3.0.1 )`

**Comment by cozzin** [comment]
Oh, I found it https://docs.tuist.io/guides/version-management/#local

**Comment by cozzin** [comment]
As @dogo mentioned, this workflow works in tuist 3.0.1 version.
But I hope this workflow supports the newest tuist version.
@pepicrft If you know about the reason for this error. Could you help us?  🙏 🙏

**Comment by Mindohyeon** [comment]
During tuist action CI, I have this Error.
```Error: command failed: /Users/runner/work/Project_name/tuistexec fetch```

> Oh, I found it https://docs.tuist.io/guides/version-management/#local

It was very helpful
